# -*- coding: utf-8 -*-
"""interface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E7Xst6Z6b4XlGKTsH56n4cvsCMtZpWxl

# 🎨 Interfaz de Colorización de Imágenes con IA

Esta interfaz te permite:
- 🔍 **Detectar automáticamente** tus 4 modelos entrenados (.h5)
- 📷 **Cargar imágenes** en blanco y negro
- 🎨 **Colorizar** con el modelo seleccionado
- 💾 **Guardar** resultados automáticamente
- 📊 **Visualizar** comparaciones lado a lado

¡Perfecto para probar tus modelos entrenados en Google Colab!
"""

# 📦 IMPORTACIONES Y CONFIGURACIÓN INICIAL
import numpy as np
import cv2
import matplotlib.pyplot as plt
from pathlib import Path
import tensorflow as tf
from PIL import Image as PILImage
import glob
import os
from datetime import datetime
import random

# Configurar matplotlib para mejor visualización
plt.style.use('default')
plt.rcParams['figure.figsize'] = (15, 6)
plt.rcParams['figure.dpi'] = 100

print("✅ Librerías importadas correctamente")
print(f"🔧 TensorFlow: {tf.__version__}")
print(f"📁 Directorio actual: {Path.cwd()}")

# 🤖 DETECCIÓN Y CARGA AUTOMÁTICA DE MODELOS
print("🔍 BUSCANDO MODELOS ENTRENADOS...")
print("=" * 40)

# Buscar archivos .h5 en el directorio actual
model_files = glob.glob("*.h5")

if not model_files:
    print("❌ No se encontraron archivos .h5")
    print("💡 Asegúrate de haber descargado los modelos de Google Colab")
    print("📋 Los archivos deben estar en el mismo directorio que este notebook")
    loaded_models = {}
else:
    print(f"📥 Encontrados {len(model_files)} archivos de modelo:")
    for f in model_files:
        print(f"   • {f}")

    loaded_models = {}

    # Cargar cada modelo
    for model_file in model_files:
        try:
            print(f"\n📥 Cargando: {model_file}")

            # Cargar modelo sin compilar (más rápido)
            model = tf.keras.models.load_model(model_file, compile=False)

            # Crear nombre descriptivo
            model_name = Path(model_file).stem

            # Asignar nombres más descriptivos basados en el archivo
            if "basica" in model_name.lower() or "basic" in model_name.lower():
                display_name = " U-Net Básica"
            elif "mejorada" in model_name.lower() or "improved" in model_name.lower():
                display_name = " U-Net Mejorada"
            elif "rmsprop" in model_name.lower():
                display_name = " U-Net RMSprop"
            elif "Profunda" in model_name.lower():
                display_name = " U-Net RMSprop"
            elif "demo" in model_name.lower():
                display_name = " Modelo Demo"
            else:
                # Usar el nombre del archivo limpio
                display_name = model_name.replace('_', ' ').title()

            loaded_models[display_name] = model

            # Mostrar información del modelo
            print(f"✅ Cargado como: {display_name}")
            print(f"   📊 Parámetros: {model.count_params():,}")
            print(f"   📐 Entrada: {model.input.shape}")
            print(f"   📐 Salida: {model.output.shape}")

        except Exception as e:
            print(f"❌ Error cargando {model_file}: {str(e)}")
            continue

    print(f"\n🎯 RESUMEN DE CARGA:")
    print(f"✅ Modelos cargados exitosamente: {len(loaded_models)}")
    print("📋 Lista de modelos disponibles:")
    for i, name in enumerate(loaded_models.keys(), 1):
        print(f"   {i}. {name}")

if loaded_models:
    print(f"\n🎉 ¡{len(loaded_models)} modelos listos para colorización!")
else:
    print("\n⚠️  No se cargaron modelos. Verifica que los archivos .h5 estén presentes.")

# 🎨 INTERFAZ CORREGIDA CON WIDGETS (Versión 2.0)
# ===============================================
import ipywidgets as widgets
from IPython.display import display, clear_output
import io


class ColorizadorCorregido:
    def __init__(self, modelos_cargados):
        """Interfaz corregida para manejar archivos subidos correctamente"""
        self.modelos = modelos_cargados
        self.directorio_salida = Path("mis_imagenes_colorizadas")
        self.directorio_salida.mkdir(exist_ok=True)

        # Crear widgets
        self.crear_widgets()

    def crear_widgets(self):
        """Crea todos los widgets de la interfaz"""

        # Título
        self.titulo = widgets.HTML(
            value="""
            <div style="text-align: center; background: linear-gradient(45deg, #ff6b6b, #4ecdc4);
                        padding: 20px; border-radius: 10px; margin-bottom: 20px;">
                <h1 style="color: white; margin: 0;"> Colorización IA - Versión Corregida</h1>
                <p style="color: white; margin: 5px 0 0 0;">Compatible con todos los formatos de widgets</p>
            </div>
            """
        )

        # Selector de modelo
        self.selector_modelo = widgets.Dropdown(
            options=list(self.modelos.keys()),
            value=list(self.modelos.keys())[0],
            description=' Modelo:',
            style={'description_width': '100px'},
            layout=widgets.Layout(width='400px')
        )

        # Subida de archivo
        self.subir_archivo = widgets.FileUpload(
            accept='image/*',
            multiple=False,
            description=' Subir Imagen',
            layout=widgets.Layout(width='300px')
        )

        # Botón de colorizar
        self.boton_colorizar = widgets.Button(
            description=' ¡Colorizar!',
            button_style='success',
            layout=widgets.Layout(width='200px', height='50px')
        )

        # Botón alternativo con explorador
        self.boton_explorador = widgets.Button(
            description=' Explorador',
            button_style='info',
            layout=widgets.Layout(width='150px', height='40px')
        )

        # Área de resultados
        self.area_resultados = widgets.Output()

        # Conectar eventos
        self.boton_colorizar.on_click(self.colorizar_imagen_corregida)
        self.boton_explorador.on_click(self.usar_explorador)

    def colorizar_imagen_corregida(self, boton):
        """Función corregida para procesar archivos subidos"""
        with self.area_resultados:
            clear_output()

            if not self.subir_archivo.value:
                print(" Por favor sube una imagen primero")
                return

            try:
                print(" Analizando archivo subido...")

                # Obtener datos del archivo (manejo múltiple de formatos)
                datos_imagen = None
                nombre_archivo = "imagen_subida"

                # Formato 1: Tupla con objetos UploadedFile
                if isinstance(self.subir_archivo.value, tuple) and len(self.subir_archivo.value) > 0:
                    archivo = self.subir_archivo.value[0]

                    # Comprobar si es un objeto con atributos .data y .name
                    if hasattr(archivo, 'data') and hasattr(archivo, 'name'):
                        datos_imagen = archivo.data
                        nombre_archivo = archivo.name
                        print(" Formato: Tupla con UploadedFile")

                    # Comprobar si es un diccionario
                    elif isinstance(archivo, dict) and 'content' in archivo:
                        datos_imagen = archivo['content']
                        nombre_archivo = archivo.get('metadata', {}).get('name', 'imagen_subida')
                        print(" Formato: Tupla con diccionario")

                # Formato 2: Diccionario directo
                elif isinstance(self.subir_archivo.value, dict):
                    primer_archivo = list(self.subir_archivo.value.values())[0]
                    datos_imagen = primer_archivo['content']
                    nombre_archivo = primer_archivo.get('metadata', {}).get('name', 'imagen_subida')
                    print(" Formato: Diccionario directo")

                if datos_imagen is None:
                    print(" No se pudo extraer datos de la imagen")
                    print(f" Tipo de valor: {type(self.subir_archivo.value)}")
                    return

                print(f" Procesando: {nombre_archivo}")
                print(f" Tamaño de datos: {len(datos_imagen)} bytes")
                print(f" Modelo: {self.selector_modelo.value}")

                # Procesar imagen
                resultado = self.procesar_imagen_bytes(datos_imagen, nombre_archivo)

                if resultado:
                    self.mostrar_resultado_corregido(resultado)

            except Exception as e:
                print(f" Error procesando imagen: {str(e)}")
                print(" Intenta con el botón '📁 Explorador' como alternativa")
                import traceback
                print(" Detalles técnicos:")
                print(traceback.format_exc())

    def usar_explorador(self, boton):
        """Usar explorador de archivos como alternativa"""
        with self.area_resultados:
            clear_output()
            print(" Abriendo explorador de archivos...")

            try:
                import tkinter as tk
                from tkinter import filedialog

                root = tk.Tk()
                root.withdraw()

                ruta_imagen = filedialog.askopenfilename(
                    title="Seleccionar imagen para colorizar",
                    filetypes=[
                        ("Imágenes", "*.jpg *.jpeg *.png *.bmp *.tiff"),
                        ("Todos los archivos", "*.*")
                    ]
                )

                root.destroy()

                if not ruta_imagen:
                    print(" No se seleccionó ninguna imagen")
                    return

                print(f" Imagen seleccionada: {os.path.basename(ruta_imagen)}")
                print(f" Modelo: {self.selector_modelo.value}")

                # Read file as bytes
                with open(ruta_imagen, 'rb') as f:
                    datos_imagen = f.read()

                resultado = self.procesar_imagen_bytes(datos_imagen, os.path.basename(ruta_imagen))

                if resultado:
                    self.mostrar_resultado_corregido(resultado)

            except ImportError:
                print(" tkinter no disponible")
            except Exception as e:
                print(f" Error: {str(e)}")

    def procesar_imagen_bytes(self, datos_imagen, nombre_archivo):
        """Procesa bytes de imagen y coloriza"""
        try:
            # Cargar imagen desde bytes
            imagen = PILImage.open(io.BytesIO(datos_imagen))

            # Convertir a RGB si es necesario
            if imagen.mode != 'RGB':
                imagen = imagen.convert('RGB')

            # Redimensionar
            imagen_resized = imagen.resize((128, 128))

            # Convertir a numpy array asegurando el tipo correcto
            imagen_array = np.array(imagen_resized, dtype=np.uint8)

            # Normalizar correctamente
            imagen_normalizada = imagen_array.astype(np.float32) / 255.0

            # Preparar para modelo (convertir a escala de grises)
            imagen_gris = cv2.cvtColor(imagen_normalizada.astype(np.float32), cv2.COLOR_RGB2GRAY)
            imagen_gris = np.expand_dims(imagen_gris, axis=-1)
            imagen_gris = np.expand_dims(imagen_gris, axis=0)

            # Colorizar
            modelo = self.modelos[self.selector_modelo.value]
            prediccion = modelo.predict(imagen_gris, verbose=0)
            imagen_colorizada = np.clip(prediccion[0], 0, 1)

            # Guardar
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            nombre_base = Path(nombre_archivo).stem
            modelo_limpio = self.selector_modelo.value.replace(' ', '_').replace('', '').replace('', '').replace('', '').replace('', '').strip()

            nombre_salida = f"{nombre_base}_colorizada_{modelo_limpio}_{timestamp}.png"
            ruta_salida = self.directorio_salida / nombre_salida

            imagen_colorizada_pil = PILImage.fromarray((imagen_colorizada * 255).astype(np.uint8))
            imagen_colorizada_pil.save(ruta_salida)

            return {
                'original': imagen_normalizada,  # Usar la imagen normalizada para mostrar
                'gris': imagen_gris[0, :, :, 0],
                'colorizada': imagen_colorizada,
                'modelo': self.selector_modelo.value,
                'archivo': ruta_salida
            }

        except Exception as e:
            print(f" Error en procesamiento: {str(e)}")
            return None


    def mostrar_resultado_corregido(self, resultado):
        """Muestra los resultados"""
        fig, axes = plt.subplots(1, 3, figsize=(15, 5))

        # Original
        axes[0].imshow(resultado['original'])
        axes[0].set_title(' Tu Imagen Original', fontsize=14)
        axes[0].axis('off')

        # Escala de grises
        axes[1].imshow(resultado['gris'], cmap='gray')
        axes[1].set_title(' Entrada del Modelo', fontsize=14)
        axes[1].axis('off')

        # Colorizada
        axes[2].imshow(resultado['colorizada'])
        axes[2].set_title(f' Colorizada\n{resultado["modelo"]}', fontsize=14)
        axes[2].axis('off')

        plt.tight_layout()
        plt.show()

        print(" ¡COLORIZACIÓN COMPLETADA!")
        print(f" Guardada en: {resultado['archivo']}")


    def mostrar_interfaz(self):
        """Muestra la interfaz corregida"""
        return widgets.VBox([
            self.titulo,

            widgets.HTML("<h3>🔧 Controles</h3>"),
            widgets.HBox([
                widgets.VBox([
                    widgets.HTML("<b>1 Selecciona modelo:</b>"),
                    self.selector_modelo
                ]),

                widgets.VBox([
                    widgets.HTML("<b>2 Sube imagen:</b>"),
                    self.subir_archivo
                ]),

                widgets.VBox([
                    widgets.HTML("<b>3 Colorizar:</b>"),
                    self.boton_colorizar,
                    widgets.HTML("<br>"),
                    self.boton_explorador
                ])
            ]),

            widgets.HTML("<hr style='margin: 30px 0;'>"),
            widgets.HTML("<h3> Resultados</h3>"),
            self.area_resultados
        ])

# ✅ CREAR INTERFAZ CORREGIDA
if loaded_models:
    print(" CREANDO INTERFAZ CORREGIDA...")
    try:
        colorizador_v2 = ColorizadorCorregido(loaded_models)
        display(colorizador_v2.mostrar_interfaz())

        print(" ¡INTERFAZ CORREGIDA LISTA!")
        print(" Características:")
        print("   • Manejo robusto de archivos subidos")
        print("   • Botón alternativo con explorador de archivos")
        print("   • Compatible con diferentes formatos de widgets")
        print("   • Diagnóstico mejorado de errores")

    except Exception as e:
        print(f" Error: {str(e)}")
        print(" Usa la interfaz alternativa: interfaz_simple_upload()")
else:
    print(" No hay modelos cargados. Ejecuta las celdas anteriores.")